

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const SET_REGISTER_REDIRECT_PATH = 'SET_REGISTER_REDIRECT_PATH';

export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_AVATAR_SUCCESS = 'FETCH_USER_AVATAR_SUCCESS';
export const FETCH_USER_MANAGEGROUPS_SUCCESS = 'FETCH_USER_MANAGEGROUPS_SUCCESS';
export const FETCH_USER_JOINGROUPS_SUCCESS = 'FETCH_USER_JOINGROUPS_SUCCESS';
export const FETCH_USER_MANAGECONTRACTS_SUCCESS = 'FETCH_USER_MANAGECONTRACTS_SUCCESS';
export const FETCH_USER_JOINCONTRACTS_SUCCESS = 'FETCH_USER_JOINCONTRACTS_SUCCESS';
export const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const FETCH_GROUP_START = 'FETCH_GROUP_START';
export const FETCH_GROUP_INFORMATION_SUCCESS = 'FETCH_GROUP_INFORMATION_SUCCESS';
export const FETCH_GROUP_USERS_SUCCESS = 'FETCH_GROUP_USERS_SUCCESS';
export const FETCH_GROUP_FAIL = 'FETCH_GROUP_FAIL';

export const FETCH_CONTRACT_START = 'FETCH_CONTRACT_START';
export const FETCH_CONTRACT_INFORMATION_SUCCESS = 'FETCH_CONTRACT_INFORMATION_SUCCESS';
export const FETCH_CONTRACT_USERS_SUCCESS = 'FETCH_CONTRACT_USERS_SUCCESS';
export const FETCH_ALL_CONTRACTS_SUCCESS = 'FETCH_ALL_CONTRACTS_SUCCESS';
export const FETCH_CONTRACT_FAIL = 'FETCH_CONTRACT_FAIL';
